name: FullDeploymenttoProduction

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies and build Vue app
      run: |
        cd vue
        npm install
        npm run build

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Create .env file
      run: |
        cat << EOF > .env
        APP_NAME=${{ secrets.ENV_APP_NAME }}
        APP_KEY=${{ secrets.ENV_APP_KEY }}
        APP_ENV=${{ secrets.ENV_APP_ENV }}
        APP_DEBUG=${{ secrets.ENV_APP_DEBUG }}
        APP_URL=${{ secrets.ENV_APP_URL }}
        CLIENT_SIDE_URL=${{ secrets.ENV_CLIENT_SIDE_URL }}
        LOG_CHANNEL=${{ secrets.ENV_LOG_CHANNEL }}
        LOG_DEPRECATIONS_CHANNEL=${{ secrets.ENV_LOG_DEPRECATIONS_CHANNEL }}
        LOG_LEVEL=${{ secrets.ENV_LOG_LEVEL }}
        DB_HOST=${{ secrets.ENV_DB_HOST }}
        DB_PORT=${{ secrets.ENV_DB_PORT }}
        DB_DATABASE=${{ secrets.ENV_DB_DATABASE }}
        DB_USERNAME=${{ secrets.ENV_DB_USERNAME }}
        DB_PASSWORD=${{ secrets.ENV_DB_PASSWORD }}
        BROADCAST_DRIVER=${{ secrets.ENV_BROADCAST_DRIVER }}
        CACHE_DRIVER=${{ secrets.ENV_CACHE_DRIVER }}
        FILESYSTEM_DRIVER=${{ secrets.ENV_FILESYSTEM_DRIVER }}
        QUEUE_CONNECTION=${{ secrets.ENV_QUEUE_CONNECTION }}
        SESSION_DRIVER=${{ secrets.ENV_SESSION_DRIVER }}
        SESSION_LIFETIME=${{ secrets.ENV_SESSION_LIFETIME }}
        MEMCACHED_HOST=${{ secrets.ENV_MEMCACHED_HOST }}
        REDIS_HOST=${{ secrets.ENV_REDIS_HOST }}
        REDIS_PASSWORD=${{ secrets.ENV_REDIS_PASSWORD }}
        REDIS_PORT=${{ secrets.ENV_REDIS_PORT }}
        MAIL_MAILER=${{ secrets.ENV_MAIL_MAILER }}
        MAIL_HOST=${{ secrets.ENV_MAIL_HOST }}
        MAIL_PORT=${{ secrets.ENV_MAIL_PORT }}
        MAIL_USERNAME=${{ secrets.ENV_MAIL_USERNAME }}
        MAIL_PASSWORD=${{ secrets.ENV_MAIL_PASSWORD }}
        MAIL_ENCRYPTION=${{ secrets.ENV_MAIL_ENCRYPTION }}
        MAIL_FROM_ADDRESS=${{ secrets.ENV_MAIL_FROM_ADDRESS }}
        MAIL_NAME_APP=${{ secrets.ENV_MAIL_NAME_APP }}
        MAIL_FROM_NAME=${{ secrets.ENV_MAIL_FROM_NAME }}
        AWS_ACCESS_KEY_ID=${{ secrets.ENV_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.ENV_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION=${{ secrets.ENV_AWS_DEFAULT_REGION }}
        AWS_BUCKET=${{ secrets.ENV_AWS_BUCKET }}
        AWS_USE_PATH_STYLE_ENDPOINT=${{ secrets.ENV_AWS_USE_PATH_STYLE_ENDPOINT }}
        EOF

    - name: Deploy Backend with SSH
      run: |
        ssh -o "StrictHostKeyChecking=no" -p 65002 u278888007@89.116.147.34 "cd domains/api.direktor.com.pe && git pull"

    - name: Deploy Frontend with curl 
      run: |
        cd vue/dist
        find . -type f -exec curl --ftp-create-dirs -T {} ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_SERVER }}/{} \;
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
