name: FullDeploymenttoProduction

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies and build Vue app
      run: |
        cd vue
        npm install
        npm run build

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH and Deploy Backend
      run: |
          ssh -o "StrictHostKeyChecking=no" -p 65002 u278888007@89.116.147.34 "cd domains/api.direktor.com.pe && git pull"

    - name: Install lftp for FTP upload
      run: sudo apt-get update && sudo apt-get install lftp
      
    - name: Upload Frontend via FTP
      run: |
        sudo apt-get update && sudo apt-get install lftp
        lftp -e "
          set ftp:ssl-allow no;  # Ajusta esta opción si tu servidor FTP no usa SSL/TLS
          set ssl:verify-certificate no;  # Omitir la verificación de certificados, ajusta según tu configuración
          open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -p 21 ${{ secrets.FTP_SERVER }};
          lcd ./vue/dist;  # Cambia al directorio local donde están los archivos
          mirror --reverse --delete --verbose;  # Sube y sincroniza los archivos
          bye;
        "
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
    
        
