name: FullDeploymenttoProduction

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies and build Vue app
      run: |
        cd vue
        npm install
        npm run build

    - name: Setup SSH key with passphrase
      env:
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
      run: |
        mkdir -p ~/.ssh
        # Asegura de que los caracteres de fin de línea sean correctos y guarda la clave privada
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Lista el contenido de .ssh para asegurar que el archivo está presente
        ls -lah ~/.ssh/
        # Instala expect
        sudo apt-get update && sudo apt-get install -y expect
        # Inicia el agente SSH
        eval $(ssh-agent -s)
        # Verifica que el agente SSH esté corriendo
        ssh-add -l
        # Crea el script de expect
        echo '#!/usr/bin/expect -f' > ~/.ssh/expect_ssh_add.sh
        echo 'spawn ssh-add ~/.ssh/id_rsa' >> ~/.ssh/expect_ssh_add.sh
        echo 'expect "Enter passphrase for /home/runner/.ssh/id_rsa:"' >> ~/.ssh/expect_ssh_add.sh
        echo 'send "$env(SSH_PASSPHRASE)\r"' >> ~/.ssh/expect_ssh_add.sh
        echo 'expect eof' >> ~/.ssh/expect_ssh_add.sh
        chmod +x ~/.ssh/expect_ssh_add.sh
        # Ejecuta el script de expect
        ~/.ssh/expect_ssh_add.sh

    - name: SSH and Deploy Backend and Frontend
      run: |
        ssh -o "StrictHostKeyChecking=no" -p 65002 u278888007@89.116.147.34 "cd domains/api.direktor.com.pe && git pull"
        rsync -avz --delete ./vue/dist/ u278888007@89.116.147.34:/domains/direktor.com.pe/public_html/
